"""add must_change_password to user

Revision ID: 548838d22b25
Revises: 5d9318582655
Create Date: 2026-01-24 23:31:40.437956

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '548838d22b25'
down_revision = '5d9318582655'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('must_change_password', sa.Boolean(), nullable=False, server_default=sa.false()))
        batch_op.alter_column('must_change_password', server_default=None)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('must_change_password')

    # ### end Alembic commands ###
